const fs=require('fs'),vm=require('vm'),assert=require('assert');
const nodes=new Map();function parse(s){for(const m of s.matchAll(/<(input|select|div|button)[^>]*\bid="([^"]+)"[^>]*>([\s\S]*?)(?:<\/select>|$)/g)){};for(const m of s.matchAll(/\bid="([^"]+)"/g))if(!nodes.has(m[1]))nodes.set(m[1],new El(m[1]));for(const m of s.matchAll(/<input[^>]*\bid="([^"]+)"[^>]*>/g)){nodes.get(m[1]).value=(m[0].match(/value="([^"]*)"/)||[])[1]||'';nodes.get(m[1]).checked=m[0].includes('checked')}for(const m of s.matchAll(/<select[^>]*\bid="([^"]+)"[^>]*>([\s\S]*?)<\/select>/g))nodes.get(m[1]).innerHTML=m[2]}
class El{constructor(id){this.id=id;this.value='';this.style={};this.dataset={};this.listeners={};this.classList={add(){},remove(){},toggle(){}}}set innerHTML(s){this.html=s;parse(s);if(s.startsWith('<option')){const opt=[...s.matchAll(/<option value="([^"]*)"([^>]*)>/g)];this.value=(opt.find(x=>x[2].includes('selected'))||opt[0]||[])[1]||''}}get innerHTML(){return this.html||''}addEventListener(t,f){this.listeners[t]=f}querySelector(){return {prepend(){},textContent:''}}querySelectorAll(){return []}showModal(){this.open=true}close(){this.open=false}remove(){nodes.delete(this.id)}insertAdjacentHTML(_,s){this.innerHTML+=s}}
const html=fs.readFileSync(require('path').join(__dirname, '../web/index.html'),'utf8');parse(html.split('<script>')[0]);let js=html.match(/<script>([\s\S]*?)<\/script>/)[1];js=js.slice(0,js.lastIndexOf("(async()=>{try{const s=await api('/api/session');"));
const ctx=vm.createContext({document:{getElementById:id=>nodes.get(id)||null,addEventListener(){},createElement:()=>new El('new'),querySelectorAll(){return []}},console,Date,setTimeout,clearTimeout,location:{},fetch(){throw Error('Unexpected fetch')},confirm:()=>true});vm.runInContext(js,ctx);
const fixture={boot:{terapistler:[{id:3,ad:'Terapist',aktif:1}],hizmetler:[{id:11,terapist_id:3,kategori:'pilates',alan_adi:'Pilates',aktif:1}],danisanlar:[{id:1,ad:'Ayşe',soyad:'Test',telefon:'555'}],odalar:[],paketler:[]},data:{uyeler:[{id:1,ad:'Ayşe',soyad:'Test',telefon:'555'}],paketler:[{id:1,danisan_id:1,danisan_adi:'Ayşe Test',ad:'8 + 2',aktif:1,grup_turu:'grup2',fiyat:4000,seans_sayisi:8,hediye_seans:2,kalan:10,kullanilan:0,hediye_kullanilan:0,tahsilat:0,bakiye:4000,baslangic:'2026-01-01',bitis:'2027-12-31'}],tarifeler:[{id:1,ad:'Tarife',aktif:1,seans_sayisi:8,hediye_seans:2,hafta:6,bireysel:6400,grup2:4000,grup3:3200}],planlar:[]}};ctx.fixture=fixture;
vm.runInContext("state.boot=fixture.boot;state.boot.paketler=fixture.data.paketler;state.pilatesData=fixture.data;state.page='pilates';boot=async()=>{};api=async(path)=>fixture.data;",ctx);
(async()=>{
fixture.boot.terapistler=[{id:1,ad:'A',soyad:'Bir',aktif:1},{id:2,ad:'B',soyad:'İki',aktif:1}];fixture.boot.hizmetler=[{id:1,terapist_id:1,terapist_ids:[1,2],terapist_adi:'A, B',alan_adi:'Ortak',kategori:'ftr',aktif:1,seans_ucreti:1000}];
await vm.runInContext("openEditor('hizmetler',fixture.boot.hizmetler[0])",ctx);let fields=nodes.get('fields').innerHTML;assert.equal((fields.match(/name=\"service_therapists\"/g)||[]).length,2);assert.equal((fields.match(/name=\"service_therapists\" value=\"[12]\" checked/g)||[]).length,2);
await vm.runInContext("openProgram({danisan_id:1,terapist_id:2,hizmet_id:1})",ctx);vm.runInContext("$('f-pg-package').value='';state.page='planlar';programServices(1)",ctx);assert(!nodes.get('f-pg-service').innerHTML.includes('Ortak'));
const menu=vm.runInContext("renderList('hizmetler',fixture.boot.hizmetler)",ctx);assert(menu.includes('Yönet'));assert(menu.includes('Terapistleri seç'));
const packages=vm.runInContext("renderList('paketler',fixture.data.paketler)",ctx);assert(packages.includes('package-delete-direct'));assert(packages.includes('Düzenle'));
vm.runInContext("state.calendarItems=[{danisan_id:1,danisan_adi:'Ayşe Test',terapist_id:3,hizmet_id:11,tarih:'2026-01-05',saat:'10:00',sure_dk:45,oda_id:1,paket_id:1,grup_turu:'grup2',kaynak:'planli'}];state.page='planlar';$('program-editor').close();boot=async()=>{};renderProgramCalendar=async()=>{}",ctx);let attendance=null;ctx.api=async(path,data)=>{attendance={path,data};return {ok:true}};await ctx.markProgramAttendance(0);assert.equal(attendance.path,'/api/save');assert.equal(attendance.data.kind,'seanslar');assert.equal(attendance.data.data.danisan_id,1);assert.equal(attendance.data.data.conflict_override,1);assert.equal(nodes.get('program-editor').open,false);vm.runInContext("state.calendarItems=[{id:10,danisan_id:1,terapist_id:3,hizmet_id:11,tarih:'2026-01-05',saat:'10:00',sure_dk:45,oda_id:1,paket_id:1,grup_turu:'grup2',kaynak:'planli'},{id:11,danisan_id:2,terapist_id:3,hizmet_id:11,tarih:'2026-01-05',saat:'10:00',sure_dk:45,oda_id:1,paket_id:2,grup_turu:'grup2',kaynak:'planli'}]",ctx);attendance=null;ctx.api=async(path,data)=>{attendance={path,data};return {id:{members:2}}};await ctx.markGroupAttendance('0,1');assert.equal(attendance.data.kind,'grup_katilim');assert.equal(attendance.data.data.uyeler.length,2);
assert(fs.readFileSync(require('path').join(__dirname,'../web/index.html'),'utf8').includes("btn('Geldi','p-attend'"));assert(fs.readFileSync(require('path').join(__dirname,'../web/index.html'),'utf8').includes("btn('Geldi','p-group-attend'"));
console.log('PASS: Pilates-only program service, direct attendance save without opening an editor, service management and package controls.');
})().catch(e=>{console.error(e);process.exitCode=1});

